encoding: utf-8

# SEO相关信息
title: zhangchang的Blog
description: zhangchang的Blog
keywords: Java, 数据结构, 算法, 多线程, 设计模式, spring, Http
author: zhangchang

# 项目环境
# 静态资源找不到，链接点进去不对时请检查下这里的配置
# demo.com访问设置为""，demo.com/blog/访问设置为"/blog"
context: ""

# 用来生成sitemap
siteMapPrefix: "https://www.zhangchangbao.com"

## 文章url前缀，固定格式，不要动
permalink: /posts/:year/:month/:day/:title.html

# 页面底部信息
copyright: 2018
record: "京A00001号"

coderay:
  coderay_tab_width: 4

# Gitalk settings
comment_gitalk_clientId: cd9e988dce5113b6026b
comment_gitalk_clientSecret: f90642dc6b14c8236e0058744a18759c739f0a6e
comment_gitalk_repo: https://github.com/changboa66/github-pages-comments
github_username: changboa_66
