encoding: utf-8

# seo
title: TMaize'Blog
description: TMaize'Blog
keywords: TMaize,Blog,Java,Android,Html,Css,Js,算法
author: TMaize

# "","/blog"
context: ""
"siteMapPrefix": "http://blog.tmaize.net"

## 文章url前缀 context/自定义，下面的context为''
permalink: /posts/:year/:month/:day/:title.html

copyright: 2016
record: "皖ICP备16016174号"

coderay:
  coderay_tab_width: 4