encoding: utf-8

# SEO相关信息
title: TMaize Blog
description: TMaize的个人博客
keywords: TMaize,Blog,Java,Html,JavaScript
author: TMaize
footerText: 'Copyright © 2016 皖ICP备16016174号'

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://blog.tmaize.net'
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/86335

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 显示访问量统计，由不蒜子提供服务
extCount: false

# 友情链接
links:
  - title: 文科中的技术宅
    url: https://www.townwang.com
  - title: Auuu Nya Blog
    url: http://mu1er.cn
  - title: 春风十里
    url: https://www.geek-era.com
  - title: 阿川的个人博客
    url: https://achuan.io
  - title: 魏文成博客
    url: https://www.wwc.ren
  - title: 06m
    url: https://www.06m.me
  - title: 达达知识
    url: https://www.dadapush.com
  - title: 祈雨的博客
    url: https://wakzz.cn
  - title: hongCYu’s Blog
    url: https://hongcyu.cn
  - title: Sorryfu
    url: https://fushaolei.github.io
  - title: 简单的人生笔记
    url: https://yoyling.com
  - title: oneNeko的博客
    url: https://blog.oneneko.com
  - title: Py's Whisper
    url: https://whisper.pyliubaolin.top
  - title: Yuyao's Blog
    url: http://hellocode.ink
  - title: 木叶的博客
    url: https://muye.ml
  - title: Stansec
    url: https://standeblog.com
  - title: Wenn的个人博客
    url: https://wenn.tech
  - title: Congbo's Blog
    url: https://congbo.site
  - title: 咕咚同学
    url: https://gudong.site
  - title: Chemcat Blog
    url: https://chemcat.gitee.io
  - title: 大葱博客
    url: https://blog.zzzdc.com/
